"""alert claim columns

Revision ID: 23f75cceb59e
Revises: ecb1286f0beb
Create Date: 2026-10-03 18:22:04.354010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f75cceb59e'
down_revision: Union[str, Sequence[str], None] = 'ecb1286f0beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'attempts')
    op.drop_column('alerts', 'claimed_at')
    # ### end Alembic commands ###
