"""initial schema

Revision ID: ecb1286f0beb
Revises: 
Create Date: 2026-10-03 15:55:17.472026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecb1286f0beb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('project_code', sa.String(length=40), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('announce_date', sa.Date(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('provinces', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('cities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('advert_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_syllabus', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_html_path', sa.Text(), nullable=True),
    sa.Column('parsed_text_path', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_listing_source_external_id')
    )
    op.create_index(op.f('ix_listings_kind'), 'listings', ['kind'], unique=False)
    op.create_index(op.f('ix_listings_last_date'), 'listings', ['last_date'], unique=False)
    op.create_index(op.f('ix_listings_needs_review'), 'listings', ['needs_review'], unique=False)
    op.create_index(op.f('ix_listings_source'), 'listings', ['source'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('matched_vacancy_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('matched_program_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', 'alert_type', name='uq_alert_user_listing_type')
    )
    op.create_index(op.f('ix_alerts_listing_id'), 'alerts', ['listing_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'url', name='uq_attachment_listing_url')
    )
    op.create_index(op.f('ix_attachments_listing_id'), 'attachments', ['listing_id'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kinds', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('bps_min', sa.Integer(), nullable=True),
    sa.Column('bps_max', sa.Integer(), nullable=True),
    sa.Column('fields', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('provinces', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('max_experience_years', sa.Integer(), nullable=True),
    sa.Column('program_levels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=True),
    sa.Column('subjects', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('duration', sa.String(length=30), nullable=True),
    sa.Column('eligibility', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('fee_pkr', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('via_nts', sa.Boolean(), nullable=False),
    sa.Column('test_syllabus', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_from', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_level'), 'programs', ['level'], unique=False)
    op.create_index(op.f('ix_programs_listing_id'), 'programs', ['listing_id'], unique=False)
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('post_name', sa.Text(), nullable=False),
    sa.Column('post_name_raw', sa.Text(), nullable=True),
    sa.Column('bps', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('bps_min', sa.Integer(), nullable=True),
    sa.Column('bps_max', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=30), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('total_posts_shared', sa.Boolean(), nullable=False),
    sa.Column('fee_pkr', sa.Integer(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('qualification', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('experience_years_min', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('test_syllabus', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_from', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_bps_max'), 'vacancies', ['bps_max'], unique=False)
    op.create_index(op.f('ix_vacancies_bps_min'), 'vacancies', ['bps_min'], unique=False)
    op.create_index(op.f('ix_vacancies_field'), 'vacancies', ['field'], unique=False)
    op.create_index(op.f('ix_vacancies_listing_id'), 'vacancies', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_listing_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_field'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_bps_min'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_bps_max'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_programs_listing_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_level'), table_name='programs')
    op.drop_table('programs')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_attachments_listing_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_listing_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_source'), table_name='listings')
    op.drop_index(op.f('ix_listings_needs_review'), table_name='listings')
    op.drop_index(op.f('ix_listings_last_date'), table_name='listings')
    op.drop_index(op.f('ix_listings_kind'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
